import UIKit

/**Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 */

var Array = [Int]()

var f=1
var s=2
var tp=0
var mul=0

//print(f)

//second sayım 4 milyonun altında olduğu sürece
while(s<4000000){
    if s % 2 == 0 {
        mul += s
        //çiftse topluyorum
    }
   
    //print(s)
    //seconda ilk sayıyla ikinci sayıyı toplayıp atıyorum
    //firstte second değerini alıyor
    tp=f
    f=s
    s=tp+s
    
}
print(mul)
